[tool.poetry]
name = "flask-boilerplate"
version = "0.1.0"
description = ""
authors = ["Cedric Grun <cedric.grun@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/cedric57/flask-boilerplate"
repository = "https://github.com/cedric57/flask-boilerplate"
documentation = "https://flask-boilerplate.readthedocs.io"

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.1.0"
sphinx = "^8.1.3"
jinja2 = "^3.1.5"
sqlalchemy = "^2.0.37"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
black = "^24.10.0"
isort = "^5.13.2"
flake8 = "^7.1.1"
mypy = "^1.14.1"
bandit = "^1.8.2"
safety = "^3.2.14"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
docs = ["sphinx"]

[tool.black]
required-version = '23.3.0'
line-length = 120

[tool.isort]
profile = "black"

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]
line-length=120

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E", "F"]
ignore = []
