"""Module defining an example entity in the domain layer.

Entities are domain objects that have a unique identity and lifecycle. They are defined
by their attributes and behavior, and they encapsulate business logic related to their
identity and state.

This module provides an example entity `ExampleEntity` that demonstrates how to define
entities in the domain layer. Entities typically have a unique identifier and attributes
that represent their state.
"""

from dataclasses import dataclass
from uuid import UUID

from flask_boilerplate.domain.primitives.entity import Entity  # Import de la classe abstraite Entity


@dataclass
class ExampleEntity(Entity):
    """An example entity in the domain layer.

    This entity represents a domain object with a unique identity and attributes.
    It encapsulates business logic related to its identity and state.

    Attributes:
        id (UUID): The unique identifier of the entity.
        name (str): The name of the entity.
        description (str): A description of the entity.
    """

    id: UUID
    name: str
    description: str

    def __hash__(self) -> int:
        return hash(self.id)

    def __post_init__(self) -> None:
        """
        Post-initialization hook to ensure the entity is properly initialized.
        If no ID is provided, it will be generated by the parent class `Entity`.
        """
        if self.id is None:
            super().__init__()  # Génère un nouvel UUID si l'ID n'est pas défini

    def __eq__(self, other: object) -> bool:
        """
        Compare two entities based on their unique identifier.
        Args:
            other (object): The other entity to compare with.
        Returns:
            bool: True if the entities have the same identifier, False otherwise.
        """
        if not isinstance(other, ExampleEntity):
            return NotImplemented
        return self.id == other.id  # L'égalité se base aussi sur l'UUID

    def update_name(self, new_name: str) -> None:
        """Update the name of the entity.

        Args:
            new_name (str): The new name for the entity.
        """
        self.name = new_name

    def update_description(self, new_description: str) -> None:
        """Update the description of the entity.

        Args:
            new_description (str): The new description for the entity.
        """
        self.description = new_description


# Add the class to __all__ for re-export in the parent module.
__all__ = ["ExampleEntity"]
