## To encourage contributors to use issue templates, we don't allow blank issues
blank_issues_enabled: true

contact_links:
  - name: "💬 Flask Boilerplate Discussions"
    url: "https://github.com/cedric57/flask-boilerplate/discussions/categories/q-a"
    about: "Get help, discuss features & roadmap, and share your projects"
