name: "🚀 Feature Request"
description: "Suggest an idea for this project 😻!"
title: "idea: [DESCRIPTION]"
labels: "type: feature request"
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Problem Statement"
      description: "Describe the problem you're facing"
      placeholder: |
        I'm always frustrated when ...

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Feature Idea"
      description: "Describe what you want instead. Examples are welcome!"
