# Nom du workflow
name: Build Package

# Événements qui déclenchent le workflow
on:
  workflow_run:
    workflows: ["Code Quality & Tests", "Security Checks"]
    types:
      - completed

# Définition des jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:  # Liste des étapes à exécuter dans le job
      - name: Check status of quality and security workflows
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
            echo "Quality or Security checks failed. Aborting build."
            exit 1
          fi

      - name: Set up Python and Poetry
        uses: ./.github/actions/install-env

      - name: Run tests  # Étape pour exécuter les tests
        run: poetry run pytest  # Exécuter les tests avec Pytest via Poetry
