name: CD Production

on:
  push:
    branches:
      - main # Déclenché après un merge dans main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to production
        env:
          PROD_API_KEY: ${{ secrets.PROD_API_KEY }}
        run: ./deploy-to-prod.sh

      - name: Create Git tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag -a v$(date +%Y.%m.%d) -m "Release ${{ github.sha }}"
          git push origin --tags
