name: CI Hotfixes

on:
  pull_request:
    branches:
      - "hotfix/**"
    types: [closed]

jobs:
  test-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v5 # Récupère le code source du dépôt
        with:
          ref: ${{ github.event.pull_request.base.ref }} # Branche hotfix mergée

      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v6 # Configure la version de Python spécifiée
        with:
          python-version: ${{ matrix.python-version }}

      #----------------------------------------------
      #       install & configure poetry
      #----------------------------------------------
      - name: Install Python poetry
        uses: snok/install-poetry@v1 # Installe Poetry pour gérer les dépendances
        with:
          virtualenvs-create: true # Crée un environnement virtuel
          virtualenvs-in-project: true # Place l'environnement virtuel dans le projet
          virtualenvs-path: .venv # Chemin de l'environnement virtuel
          installer-parallel: true # Active l'installation parallèle des dépendances

      - name: Verify Poetry installation
        run: poetry --version # Vérifie que Poetry est correctement installé

      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        shell: bash
        run: |
          poetry lock # Met à jour le fichier poetry.lock
          poetry install --no-interaction --no-root # Installe les dépendances sans interaction utilisateur

      - name: Run tests
        run: poetry run pytest

      - name: Deploy hotfix to prod
        if: success()
        env:
          PROD_API_KEY: ${{ secrets.PROD_API_KEY }}
        run: ./deploy-hotfix.sh
