# Nom du workflow
name: Security Checks

# Événements qui déclenchent le workflow
on:
  push:  # Lorsque du code est poussé
    branches:
      - main  # Sur la branche principale
  pull_request:  # Lorsqu'une pull request est ouverte
    branches:
      - main  # Sur la branche principale

# Définition des jobs
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python and Poetry
        uses: ./.github/actions/install-env

      - name: Security analysis with Bandit
        run: poetry run bandit .

      - name: Dependency vulnerability check with Safety
        uses: pyupio/safety-action@v1
        with:
          api-key: ${{ secrets.SAFETY_API_KEY }}

      - name: Security analysis with Snyk
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
